version: "3.7"

services:
  nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - ${NGINX_HTTP_PORT}:80
    volumes:
      - ./:/var/www/html:cached
      - .docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - php
  php:
    build:
      context: .docker/php
      dockerfile: php.local.dockerfile
    restart: unless-stopped
    volumes:
      - ./:/var/www/html:cached
